version: '3'
services:

  googlecloud:
    image: google/cloud-sdk:latest
    entrypoint: gcloud beta emulators pubsub start --host-port=googlecloud:8085 --verbosity=debug --log-http
    restart: always
    ports:
      - "8085:8085"
