[CommonVariables]
GithubOrg = "ThreeDotsLabs"
URLTemplate = "git@github.com:{{ .GithubOrg }}/{{ .Name }}.git"

#[[repositories]]
#Name = "watermill"
#HumanName = "Watermill AMQP Pub/Sub"
#URL = "{{ .URLTemplate }}"
#Templates = ["license", "common"]

[[repositories]]
Name = "watermill-amqp"
HumanName = "Watermill AMQP Pub/Sub"
URL = "{{ .URLTemplate }}"
Templates = ["license", "common", "pubsub"]

[[repositories]]
Name = "watermill-googlecloud"
HumanName = "Watermill Google Cloud Pub/Sub"
URL = "{{ .URLTemplate }}"
Templates = ["license", "common", "pubsub"]


[[repositories]]
Name = "watermill-http"
HumanName = "Watermill HTTP Pub/Sub"
URL = "{{ .URLTemplate }}"
Templates = ["license", "common", "pubsub"]

[[repositories]]
Name = "watermill-io"
HumanName = "Watermill io.Reader/io.Writer Pub/Sub"
URL = "{{ .URLTemplate }}"
Templates = ["license", "common", "pubsub"]


[[repositories]]
Name = "watermill-kafka"
HumanName = "Watermill Kafka Pub/Sub"
URL = "{{ .URLTemplate }}"
Templates = ["license", "common", "pubsub"]


[[repositories]]
Name = "watermill-nats"
HumanName = "Watermill NATS Pub/Sub"
URL = "{{ .URLTemplate }}"
Templates = ["license", "common", "pubsub"]


[[repositories]]
Name = "watermill-sql"
HumanName = "Watermill SQL Pub/Sub"
URL = "{{ .URLTemplate }}"
Templates = ["license", "common", "pubsub"]

    [repositories.Variables]
        MakefileCustom = '''
mycli:
	@mycli -h 127.0.0.1 -u root -p secret
'''