version: '3'
services:
  shop:
    image: threedotslabs/golang-librdkafka:1.11.2-stretch
    restart: on-failure
    depends_on:
    - kafka
    volumes:
    - $GOPATH/:/go/
    working_dir: /app
    command: go run /go/src/github.com/ThreeDotsLabs/watermill/_examples/abandoned-cart/shop/main.go

#  listener:
#    image: threedotslabs/golang-librdkafka:1.11.2-stretch
#    restart: on-failure
#    depends_on:
#    - kafka
#    volumes:
#    - ./shop/:/app
#    working_dir: /app
#    command: go run main.go
#
#  mailer:
#    image: threedotslabs/golang-librdkafka:1.11.2-stretch
#    restart: on-failure
#    depends_on:
#      - kafka
#    volumes:
#      - ./mailer/:/app
#    working_dir: /app
#    command: go run main.go

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    logging:
      driver: "none"

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    depends_on:
    - zookeeper
    logging:
      driver: "none"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"