apiVersion: v1
kind: Pod
metadata:
  name: benchmark
spec:
  containers:
  - name: benchmark
    image: threedotslabs/watermill-benchmark
    env:
      - name: WATERMILL_KAFKA_BROKER
        value: my-kafka:9092
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
